---
# defaults file for curator

config_path: /etc/curator

enable_aws_es: false

actions: []

client:
  hosts: ['localhost']
  port: 9200
  use_ssl: false
  ssl_no_validate: false
  timeout: 30

logging:
  loglevel: INFO
  logfile: /var/log/curator.log
  logformat: json
  blacklist: ['elasticsearch', 'urllib3']
